### ISSUE TITLE
Invalid data in output from detector

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/apriltag_kinect2#10]
RViz is complaining on a regular basis about invalid data in the exported markers:

```
Contains invalid floating point values (nans or infs)
```

Given that the same transforms are used when exporting the detections themselves, this ought to be addressed.

**Comment by dmcconachie** [comment]
@chichengumich If I could get you to look into this that would be great. The [Rosbag Recordings](https://www.dropbox.com/sh/xrszx6rsskz2456/AADXuPgqKjZUHw9k6A1fFEWoa?dl=0) folder has a bag file where the problem appears. (Or it will once the file finishes uploading).

**Comment by cheng-chi** [comment]
I almost forgot about this. Will do.

**Comment by cheng-chi** [comment]
Fixed with Nan rejection and 5x5 window search.
See commit 38d904da94c334b539053c6d9bcddb5d72bc2319.
